spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springjdbc
    username: sairam
    password: sairam
  jpa:
    show-sql: true
    generate-ddl: false
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp