spring:
  application:
    name: Demo
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  jmx:
    enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springjdbc
    username: sairam
    password: sairam
server:
  port: 8082
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
      base-path: /accesspoints
  info:
    env:
      enabled: true
  endpoint:
    health:
      show-details: never
      show-components: never
      group:
        customeAct:
          include:
          - db
          - paymentService
          - ping
#info:
#  name: Demo
#  Author: Sairam
#  Role: Developer
#  GitLink: https://github.com/sairam566
payment:
  service:
    url: https://google.com